### ISSUE TITLE
Throws when missing CLI

### ISSUE THREAD

**Issue by bcomnes** [BestBuyAPIs/bestbuy-cli#6]
```
bret-netlify:~ bret$ bestbuy-cli categories
/usr/local/lib/node_modules/bestbuy-cli/node_modules/bestbuy/index.js:14
  if (!options.key) throw new Error('A Best Buy developer API key is required');
                    ^

Error: A Best Buy developer API key is required
    at bestbuy (/usr/local/lib/node_modules/bestbuy-cli/node_modules/bestbuy/index.js:14:27)
    at run (/usr/local/lib/node_modules/bestbuy-cli/index.js:13:13)
    at cli (/usr/local/lib/node_modules/bestbuy-cli/bin.js:104:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/bestbuy-cli/bin.js:108:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
```

Not sure if you want to stack trace or not here.

**Comment by Flet** [comment]
Ah nice, I'll clean this up!
